sudo: required
dist: xenial
language: go

services:
 - docker

script:
 - docker pull hello-world
 - docker run -d hello-world
 - docker ps
 - ./hello_docker.sh

after_script:
 - echo "Image built and run successfully"
 
